### PR TITLE
Updated settings and imports to support Django>=1.11

### PR DESCRIPTION
**Pull request by chrisspen**

### CODE REVIEW

**Comment by chrisspen** [comment]
This should resolve issue #2.

**Comment by grantmcconnaughey** [comment]
This is great. Thanks!

**Comment by chrisspen** [comment]
I'd like to deploy this in a production system sometime in the next couple weeks. Do you think you could publish a fresh release to PyPI?

**Comment by grantmcconnaughey** [comment]
[Version 0.5.0 is on PyPI now.](https://pypi.python.org/pypi/django-lazy-tags)

**Pull request merged**
